
import { StatusProvider } from '@/app/context/contextStatus';
import { Inter } from 'next/font/google';
import "react-loading-skeleton/dist/skeleton.css";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import BottomFooterNavbar from './components/BottomFooterNavbar';

import ShoppingCart from './components/ShoppingCart';

import "react-tabs/style/react-tabs.css";


import Header from './components/Header';
import './globals.css';
import Footer from './components/Footer';







const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'OGERIO',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {


  return (
    <html lang="en">
      <body className={inter.className}>
        <StatusProvider>
           <Header />
          {children}
          <ShoppingCart />
         <Footer />
          <BottomFooterNavbar />
          <ToastContainer
            position="top-right"
            autoClose="1500"
            hideProgressBar={false}
            closeOnClick={true}
            pauseOnHover
            draggable={true}
          />
        </StatusProvider>
      </body>
    </html>
  );
}
